version: "3.9"

services:
  neosaas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neosaas
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
